version: "3.8"
services:
  client:
    container_name: ui
    build:
      context: ./ui
    ports:
      - "3000:3000"
  server:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
